# Generated by Django 4.0.4 on 2022-09-20 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_main', '0012_alter_jobmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalEarnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_earned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
