# Generated by Django 4.0.4 on 2022-09-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0015_alter_offeredtodothejobmodel_offer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredtodothejobmodel',
            name='offer_sended_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
