# Generated by Django 4.0.4 on 2022-09-20 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_main', '0016_offeredtodothejobmodel_offer_sended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(related_name='chat_room_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Running', 'Running'), ('Submitted', 'Submitted'), ('Completed', 'Completed')], default='Requested', max_length=100),
        ),
    ]
