# Generated by Django 4.0.4 on 2022-09-21 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_main', '0019_alter_productsubmissionmodel_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('from_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeedback_from_job', to='App_main.jobmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeedback_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
