# Generated by Django 4.0.4 on 2022-09-21 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_auth', '0009_alter_buyerprofilemodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofilemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', related_query_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
