# Generated by Django 4.0.4 on 2022-09-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0010_alter_freelancerprofilemodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='freelancerprofilemodel',
            name='feedback',
            field=models.ManyToManyField(blank=True, to='App_auth.feeedbackmodel'),
        ),
    ]
