# Generated by Django 4.0.4 on 2022-09-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0012_remove_freelancerprofilemodel_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofilemodel',
            name='feedback',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FeeedbackModel',
        ),
    ]
