# Generated by Django 4.0.4 on 2022-09-21 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_auth', '0013_alter_freelancerprofilemodel_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofilemodel',
            name='feedback',
        ),
        migrations.CreateModel(
            name='FeeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeedback_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
