# Generated by Django 4.0.4 on 2022-09-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0014_remove_freelancerprofilemodel_feedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeeedbackModel',
        ),
    ]
